DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS connections;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE connections (
    action_name TEXT NOT NULL,
    count INTEGER,
    last_connection TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
